--Made by XxRobbby @ ROBLOX or Robbie#3400 on discord. Simple script made with remotes
game.Workspace.RapperChatting:FireServer("Please wait")
wait(3)
game.Workspace.RapperChatting:FireServer("Loading.")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading..")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading...")
wait(0.5)
game.Workspace.RapperChatting:FireServer("Loading.")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading..")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading...")
wait(0.5)
game.Workspace.RapperChatting:FireServer("Loading.")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading..")
wait(1)
game.Workspace.RapperChatting:FireServer("Loading...")
wait(4)
game.Workspace.RapperChatting:FireServer("Now running Auto Rap Battle Spam Bot - Made by XxRobbby")
print("Successfully loaded - Script will only work when YOU are on stage")
wait(1)
print("You can change what it says just by editing the part after FireServer")
wait(1)
while true do
game.Workspace.RapperChatting:FireServer("I got a job with the mob, makin g’s")
wait(1)
game.Workspace.RapperChatting:FireServer("Doin some pickups, deliveries and transportin keys")
wait(1)
game.Workspace.RapperChatting:FireServer("Yeah they got me like a flunkie money")
wait(1)
game.Workspace.RapperChatting:FireServer("Did you think I was actually gonna rap, no I got tricks up my SLEEVES")
wait(3)
game.Workspace.RapperChatting:FireServer("HI GUYS ITS ALI-A HERE ")
wait(1)
game.Workspace.RapperChatting:FireServer("SING IT WITH ME")
wait(2)
game.Workspace.RapperChatting:FireServer("F")
wait(2)
game.Workspace.RapperChatting:FireServer("O")
wait(2)
game.Workspace.RapperChatting:FireServer("R")
wait(2)
game.Workspace.RapperChatting:FireServer("T")
wait(2)
game.Workspace.RapperChatting:FireServer("N")
wait(2)
game.Workspace.RapperChatting:FireServer("I")
wait(2)
game.Workspace.RapperChatting:FireServer("T")
wait(3)
game.Workspace.RapperChatting:FireServer("E")
wait(2)
game.Workspace.RapperChatting:FireServer("F IS FOR FUN WHILE YOU PLAY THE GAME")
wait(3)
game.Workspace.RapperChatting:FireServer("O IS FOR PLAYED AND THATS WHAT THE GAME IS")
wait(2)
game.Workspace.RapperChatting:FireServer("R IS FOR RATED THATS WHAT THE CRITICS SAY")
wait(4)
game.Workspace.RapperChatting:FireServer("T IS FOR TRAP BECAUSE THATS WHAT THE GAME IS")
wait(2)
game.Workspace.RapperChatting:FireServer("N IS FOR NIGHT BECAUSE THATS WHEN THE KIDS PLAY")
wait(3)
game.Workspace.RapperChatting:FireServer("I IS FOR INTERACTIVE BECAUSE ITS WHAT THE GAME LACKS")
wait(2)
game.Workspace.RapperChatting:FireServer("T IS FOR TERRIBLE BECAUSE LETS BE HONEST HERE")
wait(2)
game.Workspace.RapperChatting:FireServer("E IS FOR EXAMPLE BECAUSE I JUST GAVE AN EXAMPLE OF YOU")
wait(7)
game.Workspace.RapperChatting:FireServer("Auto Rap Over -- Restarting if there is time left --")
wait(4)
end
